### ISSUE TITLE
Allow locale 'en'

### ISSUE THREAD

**Issue by nicholaides** [tweag/cybersourcery#16]
'en' seems to be a valid locale, but the validations in `CyberSource::Profile` don't allow it.

**Comment by nicholaides** [comment]
After some research, Cybersource has 41 locales that it is documented to support. 'en' is not documented but is supported. 'en-us', 'en-gb', are documented and supported. Rather than figure out all the undocumented locales, I propose we only support those listed explicitly in the documentation, until we have a good reason not to.

**Comment by toppa** [comment]
Sounds good to me.
