### ISSUE TITLE
Why did not you use ActiveMerchant, which supports CyberSource Payment Gateway?

### ISSUE THREAD

**Issue by momelnyk** [tweag/cybersourcery#18]
Guys, why did not you use ActiveMerchant which supports CyberSource Payment Gateway? What are pros of your gem that may convince me to use it instead of ActiveMerchant CyberSource Payment Gateway?

**Comment by nicholaides** [comment]
This gem is for Silent Order Post which is different than the CyberSource Payment Gateway that ActiveMerchant supports. 

There's another project, https://github.com/activemerchant/offsite_payments that handles SOP-style interactions, but it doesn't include CyberSource, either.

**Comment by momelnyk** [comment]
Thank you.
