### ISSUE TITLE
Allow for setting of a custom reference_number in cybersource_signer 

### ISSUE THREAD

**Issue by johnkpaul** [tweag/cybersourcery#19]
If I opened a PR that allowed for this, would you consider merging? I'm trying to be able to set the reference number to a searchable, and useful number for my site.

**Comment by nicholaides** [comment]
This repo is unmaintained. 😔 You're better off forking and just using your fork.

**Comment by johnkpaul** [comment]
@nicholaides ok, thank you for letting me know. Very 😞 , but I understand.

**Comment by johnkpaul** [comment]
@nicholaides Can you add UNMAINTAINED note in the top of the README? TBH, idk if I would have chosen this library if I had known.

**Comment by nicholaides** [comment]
Will do. Sorry about that.
